apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/centos/k3/kompose convert --chart --volumes hostPath
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "9443"
    port: 9443
    targetPort: 9443
  selector:
    io.kompose.service: apigateway
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/centos/k3/kompose convert --chart --volumes hostPath
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: apigateway
  name: apigateway-localnode
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "9443"
    port: 9443
    targetPort: 9443
  selector:
    io.kompose.service: apigateway
status:
  loadBalancer: {}
