apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/centos/k3/kompose convert --chart --volumes hostPath
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: broadcaster
  name: broadcaster
spec:
  ports:
  - name: "38392"
    port: 38392
    targetPort: 38392
  selector:
    io.kompose.service: broadcaster
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/centos/k3/kompose convert --chart --volumes hostPath
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: broadcaster
  name: broadcaster-localnode
spec:
  ports:
  - name: "38392"
    port: 38392
    targetPort: 38392
  selector:
    io.kompose.service: broadcaster
status:
  loadBalancer: {}
