apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: certificator
  name: certificator
spec:
  containers:
  - env:
    - name: ENABLE_COPY_CERT
      value: "true"
    image: {{ .Values.certificator.image }}
    command: ['/bin/sh', '-c']
    args:
    - true; /copy_certs.sh;
      true; mv /usr/local/share/ca-certificates/tls.ai /usr/local/share/ca-certificates/default;
      true; mv /usr/local/share/ca-certificates/default/tls.ai.crt /usr/local/share/ca-certificates/default/default.crt;
      true; mv /usr/local/share/ca-certificates/default/tls.ai.full.pem /usr/local/share/ca-certificates/default/default.full.pem;
      true; mv /usr/local/share/ca-certificates/default/tls.ai.full.with.key.pem /usr/local/share/ca-certificates/default/default.full.with.key.pem;
      true; mv /usr/local/share/ca-certificates/default/tls.ai.key /usr/local/share/ca-certificates/default/default.key;
      true;
    name: certificator
    resources: {}
    volumeMounts:
    - mountPath: /usr/local/share/ca-certificates
      name: certificator-hostpath0
    - mountPath: /etc/localtime
      name: certificator-hostpath1
      readOnly: true
  restartPolicy: OnFailure
  imagePullSecrets:
  - name: {{ .Chart.Name }}-nvidia-registrykey-secret
  volumes:
  - hostPath:
      path: /usr/local/share/ca-certificates
    name: certificator-hostpath0
  - hostPath:
      path: /etc/localtime
    name: certificator-hostpath1
status: {}
