apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/centos/k3/kompose convert --chart --volumes hostPath
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: coturn
  name: coturn
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: coturn
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /home/centos/k3/kompose convert --chart --volumes hostPath
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: coturn
    spec:
      containers:
      - env:
        - name: COTURN_CMD
          value: -v -n --log-file stdout --min-port 50000 --max-port 50100 --no-stun
            --no-multicast-peers --fingerprint --user webrtc:webrtc --lt-cred-mech
            --realm default.svc.cluster.local --cert /usr/local/share/ca-certificates/default/default.full.pem
            --pkey /usr/local/share/ca-certificates/default/default.key
        image: {{ .Values.coturn.image }}
        name: coturn
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/coturn
          name: coturn-hostpath0
        - mountPath: /usr/local/share/ca-certificates
          name: coturn-hostpath1
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ .Chart.Name }}-nvidia-registrykey-secret
      volumes:
      - hostPath:
          path: /ssd/coturn
        name: coturn-hostpath0
      - hostPath:
          path: /usr/local/share/ca-certificates
        name: coturn-hostpath1
status: {}
