apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-crontab-pv
  labels:
    type: local
spec:
  storageClassName: {{ .Chart.Name }}-crontab-sc
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    type: DirectoryOrCreate
    path: /tmp/{{ .Chart.Name }}/crontab

