apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/centos/k3/kompose convert --chart --volumes hostPath
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: dante-proxy
  name: dante-proxy
spec:
  ports:
  - name: "1080"
    port: 1080
    targetPort: 1080
  selector:
    io.kompose.service: dante-proxy
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/centos/k3/kompose convert --chart --volumes hostPath
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: dante-proxy
  name: dante-proxy-localnode
spec:
  ports:
  - name: "1080"
    port: 1080
    targetPort: 1080
  selector:
    io.kompose.service: dante-proxy
status:
  loadBalancer: {}
