apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/prod: "true"
    io.kompose.service: memsql-schema
  name: memsql-schema
spec:
  containers:
  - env:
    - name: DB
      value: mysql
    - name: DB_ACTION
      value: update
    - name: DB_HOST
      value: memsql.default
    - name: DB_NAME
      value: tracks_db:1.21.1
    image: {{ .Values.memsqlSchema.image }}
    name: memsql-schema
    resources: {}
  restartPolicy: Never
  imagePullSecrets:
  - name: {{ .Chart.Name }}-nvidia-registrykey-secret
status: {}
