apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/centos/k3/kompose convert --chart --volumes hostPath
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: seaweedfs-volume
  name: seaweedfs-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: seaweedfs-volume
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /home/centos/k3/kompose convert --chart --volumes hostPath
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.network/prod: "true"
        io.kompose.service: seaweedfs-volume
    spec:
      containers:
      - env:
        - name: SEAWEEDFS_MODE
          value: volume
        - name: SEAWEEDFS_VOLUME
          value: "1"
        - name: SEAWEEDFS_VOLUME_CMD
          value: -port=8080 -ip=seaweedfs-volume -index=memory -max=10000000 -mserver=seaweedfs-master:9333
            -dir=/data
        - name: SEAWEEDFS_VOLUME_PORT
          value: "8080"
        image: {{ .Values.seaweedfs.image }}
        name: seaweedfs-volume
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: seaweedfs-volume-hostpath0
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ .Chart.Name }}-nvidia-registrykey-secret
      volumes:
      - hostPath:
          path: /storage/seaweed
        name: seaweedfs-volume-hostpath0
status: {}
