apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/centos/k3/kompose convert --chart --volumes hostPath
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: seaweedfs-s3
  name: seaweedfs-s3
spec:
  ports:
  - name: "8333"
    port: 8333
    targetPort: 8333
  selector:
    io.kompose.service: seaweedfs-s3
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/centos/k3/kompose convert --chart --volumes hostPath
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: seaweedfs-s3
  name: seaweedfs-s3-localnode
spec:
  ports:
  - name: "8333"
    port: 8333
    targetPort: 8333
  selector:
    io.kompose.service: seaweedfs-s3
status:
  loadBalancer: {}
