apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: {{ .Chart.Name }}-socks-pvc
  name: {{ .Chart.Name }}-socks-pvc
spec:
  storageClassName: {{ .Chart.Name }}-socks-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

